name: 'Generate update manifest'
description:
  'GitHub action to generate update manifest files for self distributed Firefox
  addons'
author: '2zqa'

inputs:
  addon-id:
    description: 'The ID of the addon to generate the update manifest for'
    required: true
  output-file:
    description: 'Path to the file to write the update manifest to'
    required: false
    default: 'updates.json'
  github-token:
    description: 'The GitHub token used to retrieve releases'
    required: false
    default: ${{ github.token }}
  repository:
    description: 'The repository to retrieve releases from'
    required: false
    default: ${{ github.repository }}

outputs:
  manifest:
    description: 'Path to the generated update manifest file'

runs:
  using: node20
  main: dist/index.js
